#!/bin/bash

# Thijs Ermens
# 11-2-2022
# Som van positieve nummers

# Vraagt om getallen, valt uit bij een negatief getal
for ((c=0; ; ))
do
	echo "Geef een getal"
	read getal
	if [[ $getal -lt 0 ]]; then
	
		# Dit berekent het gemiddelde van totaal en de count
		 deel=`echo "scale=2 ; $totaal / $c" | bc`
		 echo "Dit is deel" $deel
		 break
	else
		totaal=$(( totaal + getal ))
		c=$((c+1))
	fi
done
