#!/bin/bash

# Verkrijgen van de data
echo "Geef toetsscore 1"
read ts1
echo "Geef toetsscore 2"
read ts2 
echo "Geef toetsscore 3"
read ts3 
echo "Geef toetsscore 4"
read ts4
echo "Geef toetsscore 5"
read ts5

# berekenen van het totaal
totaal=$(($ts1 + $ts2 + $ts3 + $ts4 + $ts5))

# printen van de gemiddelde score (goed afgerond)
printf "Gemiddelde score: %d\n" $(( ($totaal + 2) / 5))

# Literatuur
# https://stackoverflow.com/questions/2395284/round-a-divided-number-in-bash
