#!/bin/bash

# Verkrijgen van de data
echo "Geef getal 1 (geen 0)"
read getal1
echo "Geef getal 2 (geen 0)"
read getal2

# Berekenen van de waardes
plus=$((getal1 + $getal2))
min=$((getal1 - $getal2))
keer=$((getal1 * getal2))
totde=$((getal1 ** getal2))
# https://www.geeksforgeeks.org/bc-command-linux-examples/
deel=`echo "scale=1 ; $getal1 / $getal2" | bc`

# Het uitvoeren van een controle, zodat de getallen niet hoger dan 9 zijn of lager dan 1
if [[ $getal1 -gt 9 ]] || [[ $getal1 -lt 1 ]] ; then
	echo "Incorrecte invoer gevonden (getal 1)"
elif [[ $getal2 -gt 9 ]] || [[ $getal2 -lt 1 ]] ; then
	echo "Incorrecte invoer gevonden (getal 2)"
else
	printf "+:	%d\n-:	%d\nx:	%d\n/:	%s\n^:	%1.1e\n" $plus $min $keer $deel $totde
fi

# https://stackoverflow.com/questions/16686819/convert-exponentials-and-rounding-numbers-in-bash
# https://stackoverflow.com/questions/38528052/how-to-transform-decimal-to-exponential-in-linux-bash
# https://stackoverflow.com/questions/2395284/round-a-divided-number-in-bash
